export const projectData = [
    {  
        id: 1,
        title: "Bazar List - Organize your Shopping List",
        description: "A shopping list app that allows users to create and share shopping lists with others.",
        description1: "Users can add items to the list, mark them as purchased, and delete them later.",
        description2: "Having a very clean and simple UI for with better experience.",
        technologies: ["Expo,", "Expo SQLite,", "React Native,", "TypeScript,", "React Navigation,"],
        github: "https://github.com/pksingh1508/bazarList_NJH",
    },
    {
        id: 2,
        title: "BookABarber - Your Personal Barber",
        description: "A mobile app that allows users to book appointments with barbers.",
        description1: "Users can view the barbers' profiles, check their availability, and book appointments.",
        description2: "Barbers can manage their schedules, view upcoming appointments, and mark them as completed.",
        technologies: ["React Native,", "Supabase,", "Google Maps API,", "TypeScript,", "Expo Router,", "Expo Location,"],
        github: "https://github.com/pksingh1508/bookabarber",
    },
    {
        id: 3,
        title: "LearniFi - An EdTech Platform",
        description: "Build an edTech Platform just like Udemy for student and teacher to collaborate.",
        description1: "Teacher have functionality to create course and launch it also have admin panels.",
        description2: "Student can enroll in course and learn from it and Give an honest review that help for other students.",
        technologies: ["React,", "JavaScript,", "Node.js,", "MongoDB,", "Express,", "Redux,", "Tailwind CSS"],
        github: "https://github.com/pksingh1508/Learnifi",
        url: "https://learnifi-seven.vercel.app",
    },
    {
        id: 4,
        title: "Hackathonwallah - Launch the Hackathons",
        description: "Build a Modern website for hosting hackathons to all over the world.",
        description1: "Online hackathons with some great prizes.",
        description2: "Anyone can participate, build, submit and win great prizes.",
        technologies: ["Next js,", "TypeScript,", "Clerk,", "Zustand,", "Tailwind CSS"],
        github: "https://github.com/pksingh1508/hackathonHub",
        url: "https://hackathonwallah.com",
    }
]
